=== KrasimirRaikov/xml/src/com/clouway/task/xmlfiles/employees.dtd
<!ELEMENT employees (Employee+)>
        <!ELEMENT Employee (firstName, lastName, age, position, employers+, addresses+)>
        <!ATTLIST Employee ID CDATA #REQUIRED>
            <!ELEMENT firstName (#PCDATA)>
            <!ELEMENT lastName (#PCDATA)>
            <!ELEMENT age (#PCDATA)>
            <!ELEMENT position (#PCDATA)>
            <!ELEMENT employers (Employer+)>
                <!ELEMENT Employer (name, startDate, endDate)>
                    <!ELEMENT name (#PCDATA)>
                    <!ELEMENT startDate (#PCDATA)>
                    <!ELEMENT endDate (#PCDATA)>
            <!ELEMENT addresses (Address+)>
                <!ELEMENT Address (street, streetNo, section, city)>
                    <!ELEMENT street (#PCDATA)>
                    <!ELEMENT streetNo (#PCDATA)>
                    <!ELEMENT section (#PCDATA)>
                    <!ELEMENT city (#PCDATA)>

=== KrasimirRaikov/xml/src/com/clouway/task/xmlfiles/task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "/home/clouway/workspaces/idea/xml/src/com/clouway/task/xmlfiles/employees.dtd">
<employees>
    <Employee ID="1">
        <firstName>Ivan</firstName>
        <lastName>Ivanov</lastName>
        <age>23</age>
        <position>mechanic</position>
        <employers>
            <Employer>
                <name>Stefan</name>
                <startDate>21-10-2010</startDate>
                <endDate>23-4-2012</endDate>
            </Employer>
            <Employer>
                <name>Ivan</name>
                <startDate>21-10-2010</startDate>
                <endDate>23-4-2012</endDate>
            </Employer>
        </employers>
        <addresses>
            <Address>
                <street>Gabrovski</street>
                <streetNo>43</streetNo>
                <section>A</section>
                <city>Veliko Tyrnovo</city>
            </Address>
        </addresses>
    </Employee>
    <Employee ID="2">
        <firstName>Kristiqn</firstName>
        <lastName>Petkov</lastName>
        <age>24</age>
        <position>programmer</position>
        <employers>
            <Employer>
                <name>Nikolai</name>
                <startDate>5-4-2015</startDate>
                <endDate>13-1-2016</endDate>
            </Employer>
            <Employer>
                <name>Ivailo</name>
                <startDate>5-4-2015</startDate>
                <endDate>13-1-2016</endDate>
            </Employer>
        </employers>
        <addresses>
            <Address>
                <street>pultava</street>
                <streetNo>12</streetNo>
                <section>B</section>
                <city>Veliko Tyrnovo</city>
            </Address>
            <Address>
                <street>pultava</street>
                <streetNo>12</streetNo>
                <section>B</section>
                <city>Veliko Tyrnovo</city>
            </Address>
        </addresses>
    </Employee>
</employees>
